
import React, { useState, useEffect, useCallback } from "react";
import { base44 } from "@/api/base44Client";
import { useMutation, useQueryClient, useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { X, Save, Plus, Trash2, AlertTriangle, RefreshCw, Info, Music, GripVertical, ArrowUp, ArrowDown, RotateCcw, Play, Image as ImageIcon, FileText, Volume2 } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { createPortal } from "react-dom";
import { componentStyles } from "@/design/componentStyles";
import MediaLinksInput from "@/components/common/MediaLinksInput";
import { normalizeMediaLinks } from "@/components/utils/media";

export default function ExerciseEditor({ ejercicio, onClose, piezaSnapshot }) {
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState({
    nombre: '',
    code: '',
    tipo: 'TC',
    duracionSeg: 0,
    instrucciones: '',
    indicadorLogro: '',
    materialesRequeridos: [],
    mediaLinks: [],
    elementosOrdenados: [],
    piezaRefId: null,
  });

  // Función para convertir el formato antiguo (media object) al nuevo (mediaLinks array)
  const normalizeMedia = (media) => {
    if (!media) return [];
    if (Array.isArray(media)) {
      // Si ya es un array, normalizarlo
      return normalizeMediaLinks(media);
    }
    // Si es un objeto, convertir a array
    const urls = [];
    if (media.video) urls.push(media.video);
    if (media.audio) urls.push(media.audio);
    if (media.imagen) urls.push(media.imagen);
    if (media.pdf) urls.push(media.pdf);
    return normalizeMediaLinks(urls);
  };
  const [nuevoMaterial, setNuevoMaterial] = useState('');
  const [saveResult, setSaveResult] = useState(null);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState(true);
  const [piezaRefId, setPiezaRefId] = useState('');
  const [selectedElementos, setSelectedElementos] = useState([]);
  const [isInlineMode, setIsInlineMode] = useState(false);

  const { data: allEjercicios = [] } = useQuery({
    queryKey: ['bloques'],
    queryFn: () => base44.entities.Bloque.list(),
  });

  const { data: piezas = [] } = useQuery({
    queryKey: ['piezas'],
    queryFn: () => base44.entities.Pieza.list(),
  });

  const piezaRef = piezas.find(p => p.id === piezaRefId);
  const usandoPiezaSnapshot = !!piezaSnapshot;
  const elementosDisponibles = usandoPiezaSnapshot ? (piezaSnapshot?.elementos || []) : (piezaRef?.elementos || []);

  const generateCode = async (tipo) => {
    const ejerciciosDeTipo = allEjercicios.filter(e => e.code?.startsWith(`${tipo}-`));
    const maxNum = ejerciciosDeTipo.reduce((max, e) => {
      const match = e.code.match(/\d+/);
      if (match) {
        const num = parseInt(match[0]);
        return num > max ? num : max;
      }
      return max;
    }, 0);
    return `${tipo}-${String(maxNum + 1).padStart(4, '0')}`;
  };

  useEffect(() => {
    if (ejercicio) {
      setIsInlineMode(true);
      setFormData({
        nombre: ejercicio.nombre || '',
        code: ejercicio.code || '',
        tipo: ejercicio.tipo || 'TC',
        duracionSeg: ejercicio.duracionSeg || 0,
        instrucciones: ejercicio.instrucciones || '',
        indicadorLogro: ejercicio.indicadorLogro || '',
        materialesRequeridos: ejercicio.materialesRequeridos || [],
        mediaLinks: normalizeMedia(ejercicio.mediaLinks || ejercicio.media),
        elementosOrdenados: ejercicio.elementosOrdenados || [],
        piezaRefId: ejercicio.piezaRefId || null,
      });
      setPiezaRefId(ejercicio.piezaRefId || '');
      setAutoGeneratedCode(false);
    } else {
      setIsInlineMode(false);
      setFormData({
        nombre: '', code: '', tipo: 'TC', duracionSeg: 0, instrucciones: '', indicadorLogro: '',
        materialesRequeridos: [], mediaLinks: [], elementosOrdenados: [], piezaRefId: null,
      });
      setPiezaRefId('');
      setSelectedElementos([]);
      generateCode('TC').then(code => {
        setFormData(prev => ({ ...prev, code }));
      });
    }
  }, [ejercicio, allEjercicios]);

  useEffect(() => {
    if (formData.tipo === 'FM' && elementosDisponibles.length > 0) {
      const initialSelected = formData.elementosOrdenados
        .map(nombre => elementosDisponibles.find(e => e.nombre === nombre))
        .filter(Boolean);
      setSelectedElementos(initialSelected);
    } else if (selectedElementos.length > 0) {
      setSelectedElementos([]);
    }
  }, [formData.tipo, formData.elementosOrdenados, elementosDisponibles]);

  useEffect(() => {
      if (formData.tipo !== 'FM' && piezaRefId) {
          setPiezaRefId('');
      }
  }, [formData.tipo, piezaRefId]);

  useEffect(() => {
    if (autoGeneratedCode && !ejercicio) {
      generateCode(formData.tipo).then(code => {
        setFormData(prev => ({ ...prev, code }));
        setAutoGeneratedCode(true);
      });
    }
  }, [formData.tipo, autoGeneratedCode, ejercicio]);

  const handleRegenerateCode = async () => {
    const newCode = await generateCode(formData.tipo);
    setFormData({ ...formData, code: newCode });
    setAutoGeneratedCode(true);
    setSaveResult({ success: true, message: '✅ Código regenerado' });
    setTimeout(() => setSaveResult(null), 2000);
  };

  const handleCodeChange = (value) => {
    setFormData({ ...formData, code: value });
    setAutoGeneratedCode(false);
  };

  const saveMutation = useMutation({
    mutationFn: async (data) => {
      if (isInlineMode) {
        return data;
      }
      
      const codeExists = allEjercicios.some(e => 
        e.code === data.code && e.id !== ejercicio?.id
      );
      if (codeExists) {
        throw new Error('Ya existe un ejercicio con este código. El código debe ser único.');
      }

      if (ejercicio?.id) {
        return base44.entities.Bloque.update(ejercicio.id, data);
      }
      return base44.entities.Bloque.create(data);
    },
    onSuccess: (result) => {
      if (isInlineMode) {
        onClose(result);
      } else {
        queryClient.invalidateQueries({ queryKey: ['bloques'] });
        setSaveResult({ success: true, message: '✅ Cambios guardados' });
        setTimeout(() => onClose(null), 1500);
      }
    },
    onError: (error) => {
      setSaveResult({ success: false, message: `❌ ${error.message}` });
    },
  });

  const handleSave = useCallback(() => {
    if (!formData.nombre.trim()) {
      setSaveResult({ success: false, message: '❌ El nombre es obligatorio' });
      return;
    }
    if (!formData.code.trim()) {
      setSaveResult({ success: false, message: '❌ El código es obligatorio' });
      return;
    }
    if (formData.duracionSeg < 0) {
      setSaveResult({ success: false, message: '❌ La duración debe ser mayor o igual a 0' });
      return;
    }
    
    let dataToSave = { ...formData };

    // Asegurarse de que se use mediaLinks en lugar de media (formato antiguo)
    if (dataToSave.media) {
      delete dataToSave.media;
    }
    // Normalizar mediaLinks al guardar
    dataToSave.mediaLinks = normalizeMediaLinks(dataToSave.mediaLinks || []);

    if (dataToSave.tipo === 'FM') {
        dataToSave.elementosOrdenados = selectedElementos.map(e => e.nombre);
        if (!usandoPiezaSnapshot) {
            dataToSave.piezaRefId = piezaRefId;
        }
    } else {
        dataToSave.elementosOrdenados = [];
        dataToSave.piezaRefId = null;
    }
    
    saveMutation.mutate(dataToSave);
  }, [formData, selectedElementos, usandoPiezaSnapshot, piezaRefId, saveMutation]);

  const addMaterial = () => {
    if (nuevoMaterial.trim()) {
      setFormData({
        ...formData,
        materialesRequeridos: [...formData.materialesRequeridos, nuevoMaterial.trim()]
      });
      setNuevoMaterial('');
    }
  };

  const removeMaterial = (index) => {
    setFormData({
      ...formData,
      materialesRequeridos: formData.materialesRequeridos.filter((_, i) => i !== index)
    });
  };

  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === '.') {
        e.preventDefault();
        onClose(null);
      }
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        e.preventDefault();
        handleSave();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose, handleSave]);

  const toggleElementoSeleccion = (elemento) => {
    if (selectedElementos.find(e => e.nombre === elemento.nombre)) {
      setSelectedElementos(selectedElementos.filter(e => e.nombre !== elemento.nombre));
    } else {
      setSelectedElementos([...selectedElementos, elemento]);
    }
  };

  const moveElemento = (index, direction) => {
    if (index + direction < 0 || index + direction >= selectedElementos.length) return;
    const newSelected = [...selectedElementos];
    [newSelected[index], newSelected[index + direction]] = [newSelected[index + direction], newSelected[index]];
    setSelectedElementos(newSelected);
  };

  const resetElementosOrden = () => {
    if (elementosDisponibles && elementosDisponibles.length > 0) {
      setSelectedElementos(elementosDisponibles.filter(availableEl => 
        selectedElementos.some(selectedEl => selectedEl.nombre === availableEl.nombre)
      ));
    } else {
      setSelectedElementos([]);
    }
  };

  const tipoLabels = {
    CA: 'Calentamiento A',
    CB: 'Calentamiento B',
    TC: 'Técnica Central',
    TM: 'Técnica Mantenimiento',
    FM: 'Fragmento Musical',
    VC: 'Vuelta a la Calma',
    AD: 'Advertencia/Descanso',
  };

  const tipoColors = {
    CA: 'bg-brand-100 text-brand-800 border-brand-200',
    CB: 'bg-blue-100 text-blue-800 border-blue-200',
    TC: 'bg-purple-100 text-purple-800 border-purple-200',
    TM: 'bg-green-100 text-green-800 border-green-200',
    FM: 'bg-pink-100 text-pink-800 border-pink-200',
    VC: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    AD: 'bg-[var(--color-surface-muted)] text-ui border-[var(--color-border-default)]',
  };

  const isAD = formData.tipo === 'AD';
  const isFM = formData.tipo === 'FM';

  const modalContent = (
    <>
      <div 
        className="fixed inset-0 bg-black/40 z-[100]"
        onClick={() => onClose(null)}
      />
      
      <div className="fixed inset-0 z-[110] flex items-center justify-center pointer-events-none p-4 overflow-y-auto">
        <div 
          className="bg-[var(--color-surface-elevated)] w-full max-w-3xl max-h-[92vh] shadow-card rounded-2xl flex flex-col pointer-events-auto my-8 border border-[var(--color-border-default)]"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="border-b border-[var(--color-border-default)] bg-[var(--color-surface-muted)] rounded-t-2xl px-6 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
              <div>
                  <h2 className="text-xl font-bold text-[var(--color-text-primary)]">
                  {isInlineMode ? 'Editar Ejercicio (inline)' : ejercicio ? 'Editar Ejercicio' : 'Nuevo Ejercicio'}
                </h2>
                  <p className="text-sm text-[var(--color-text-secondary)]">
                  {isInlineMode ? 'Cambios aplicados a la sesión actual' : 'Plantilla de ejercicio'}
                </p>
                </div>
              </div>
              <Button variant="ghost" size="icon" onClick={() => onClose(null)} className="text-[var(--color-text-primary)] hover:bg-[var(--color-surface)] h-9 w-9 rounded-xl">
                <X className="w-5 h-5" />
              </Button>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {saveResult && (
              <Alert className={`rounded-xl ${saveResult.success ? 'border-[var(--color-success)]/20 bg-[var(--color-success)]/10' : 'border-[var(--color-danger)]/20 bg-[var(--color-danger)]/10'}`}>
                <AlertDescription className="text-[var(--color-text-primary)]">
                  {saveResult.message}
                </AlertDescription>
              </Alert>
            )}

            {isFM && usandoPiezaSnapshot && (
              <Alert className="rounded-xl border-blue-200 bg-blue-50">
                <Info className="h-4 w-4 text-blue-600" />
                <AlertDescription className="text-blue-800">
                  <strong>Este FM usa el material de la Pieza de la Asignación.</strong>
                </AlertDescription>
              </Alert>
            )}

            {isAD && (
              <Alert className="rounded-xl border-[var(--color-warning)]/20 bg-[var(--color-warning)]/10">
                <AlertTriangle className="h-4 w-4 text-[var(--color-warning)]" />
                <AlertDescription className="text-[var(--color-text-primary)]">
                  Este ejercicio no activa cronómetro ni suma tiempo real. La duración es solo referencia visual.
                </AlertDescription>
              </Alert>
            )}

            <Card className="app-panel">
              <CardHeader>
                <CardTitle>Información Básica</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="tipo">Tipo de Ejercicio *</Label>
                    <Select 
                      value={formData.tipo} 
                      onValueChange={(v) => {
                        setFormData({ ...formData, tipo: v });
                        if (!ejercicio) {
                          generateCode(v).then(code => {
                            setFormData(prev => ({ ...prev, code }));
                            setAutoGeneratedCode(true);
                          });
                        }
                      }}
                      modal={false}
                    >
                        <SelectTrigger id="tipo" className="w-full h-10 rounded-xl border-[var(--color-border-default)] focus-orange">
                        <SelectValue placeholder="Selecciona un tipo..." />
                      </SelectTrigger>
                      <SelectContent 
                        position="popper" 
                        side="bottom" 
                        align="start" 
                        sideOffset={4}
                        className="z-[120] min-w-[var(--radix-select-trigger-width)] max-h-64 overflow-auto"
                      >
                        {Object.entries(tipoLabels).map(([key, label]) => (
                          <SelectItem key={key} value={key}>{label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label htmlFor="code">Código Único *</Label>
                    <div className="flex gap-2">
                      <Input
                        id="code"
                        value={formData.code}
                        onChange={(e) => handleCodeChange(e.target.value)}
                        placeholder="Ej: CA-0001"
                        className="flex-1 h-10 rounded-xl border-[var(--color-border-default)] focus-orange"
                      />
                      <Button
                        type="button"
                        variant="outline"
                        size="icon"
                        onClick={handleRegenerateCode}
                        title="Regenerar código"
                        className="h-10 w-10 rounded-xl"
                      >
                        <RefreshCw className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>

                <div>
                  <Label htmlFor="nombre">Nombre del Ejercicio *</Label>
                  <Input
                    id="nombre"
                    value={formData.nombre}
                    onChange={(e) => setFormData({ ...formData, nombre: e.target.value })}
                    placeholder="Ej: Escalas cromáticas"
                    className="h-10 rounded-xl border-[var(--color-border-default)] focus-orange"
                  />
                </div>

                <div>
                  <Label htmlFor="duracion">Duración (segundos) *</Label>
                  <Input
                    id="duracion"
                    type="number"
                    min="0"
                    value={formData.duracionSeg}
                    onChange={(e) => setFormData({ ...formData, duracionSeg: parseInt(e.target.value || 0) })}
                    className="h-10 rounded-xl border-[var(--color-border-default)] focus-orange"
                  />
                  <p className="text-xs text-[var(--color-text-secondary)] mt-1">
                    {Math.floor(formData.duracionSeg / 60)}:{String(formData.duracionSeg % 60).padStart(2, '0')} minutos
                  </p>
                </div>

                <div>
                  <Label htmlFor="instrucciones">Instrucciones</Label>
                  <Textarea
                    id="instrucciones"
                    value={formData.instrucciones}
                    onChange={(e) => setFormData({ ...formData, instrucciones: e.target.value })}
                    placeholder="Instrucciones detalladas para el ejercicio..."
                    rows={3}
                    className="rounded-xl border-[var(--color-border-default)] focus-orange resize-none"
                  />
                </div>

                <div>
                  <Label htmlFor="indicador">Indicador de Logro</Label>
                  <Input
                    id="indicador"
                    value={formData.indicadorLogro}
                    onChange={(e) => setFormData({ ...formData, indicadorLogro: e.target.value })}
                    placeholder="¿Cómo sabe el estudiante que lo logró?"
                    className="h-10 rounded-xl border-[var(--color-border-default)] focus-orange"
                  />
                </div>
              </CardContent>
            </Card>

            {isFM && (
              <Card className="app-panel">
                <CardHeader>
                  <CardTitle>
                    {usandoPiezaSnapshot ? 'Elementos de la Pieza (Asignación)' : 'Configuración FM (Previsualización)'}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {!usandoPiezaSnapshot && (
                    <div>
                      <Label htmlFor="piezaRef">Pieza de referencia (opcional)</Label>
                      <Select 
                        value={piezaRefId} 
                        onValueChange={setPiezaRefId}
                        modal={false}
                      >
                        <SelectTrigger id="piezaRef" className="w-full h-10 rounded-xl border-[var(--color-border-default)] focus-orange">
                          <SelectValue placeholder="Selecciona una Pieza para previsualizar FM (opcional)" />
                        </SelectTrigger>
                        <SelectContent 
                          position="popper" 
                          side="bottom" 
                          align="start" 
                          sideOffset={4}
                          className="z-[120] min-w-[var(--radix-select-trigger-width)] max-h-64 overflow-auto"
                        >
                          <SelectItem value={null}>Sin pieza de referencia</SelectItem>
                          {piezas.length === 0 ? (
                            <div className="p-2 text-sm text-[var(--color-text-secondary)]">No hay piezas disponibles</div>
                          ) : (
                            piezas.map(p => (
                              <SelectItem key={p.id} value={p.id}>{p.nombre}</SelectItem>
                            ))
                          )}
                        </SelectContent>
                      </Select>
                      {!piezaRefId && (
                        <p className="text-xs text-blue-600 mt-1">
                          Puedes guardar sin pieza. La configuración se aplicará al crear la Asignación.
                        </p>
                      )}
                    </div>
                  )}

                  {elementosDisponibles.length > 0 && (
                    <>
                      <div>
                        <Label>Elementos disponibles (multi-selección y ordenación)</Label>
                        <div className="border border-[var(--color-border-default)] rounded-xl p-3 max-h-48 overflow-y-auto space-y-2 bg-muted">
                          {elementosDisponibles.map((elemento) => (
                            <div 
                              key={elemento.nombre}
                              className="flex items-center gap-2 p-2 bg-card border border-[var(--color-border-default)] rounded-xl cursor-pointer hover:bg-muted hover:shadow-sm transition-all"
                              onClick={() => toggleElementoSeleccion(elemento)}
                            >
                              <Checkbox 
                                checked={!!selectedElementos.find(e => e.nombre === elemento.nombre)}
                                onCheckedChange={() => toggleElementoSeleccion(elemento)}
                              />
                              <Music className="w-4 h-4 text-pink-600" />
                              <span className="text-sm flex-1 text-ui">{elemento.nombre}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {selectedElementos.length > 0 && (
                        <>
                          <div>
                            <div className="flex items-center justify-between mb-2">
                              <Label>Orden seleccionado ({selectedElementos.length})</Label>
                              <div className="flex gap-2">
                                <Button
                                  type="button"
                                  variant="outline"
                                  size="sm"
                                  onClick={resetElementosOrden}
                                  className="h-8 rounded-xl hover:shadow-sm"
                                >
                                  <RotateCcw className="w-3 h-3 mr-1" />
                                  Restablecer
                                </Button>
                                <Button
                                  type="button"
                                  variant="outline"
                                  size="sm"
                                  onClick={() => setSelectedElementos([])}
                                  className="h-8 rounded-xl hover:shadow-sm"
                                >
                                  Vaciar
                                </Button>
                              </div>
                            </div>
                            <div className="border border-[var(--color-border-default)] rounded-xl p-3 space-y-1 bg-card">
                              {selectedElementos.map((elemento, index) => (
                                <div key={index} className="flex items-center gap-2 p-2 bg-muted rounded-xl">
                                  <div className="flex flex-col gap-0.5">
                                    <Button
                                      type="button"
                                      variant="ghost"
                                      size="icon"
                                      className="h-5 w-5 p-0 rounded"
                                      onClick={() => moveElemento(index, -1)}
                                      disabled={index === 0}
                                    >
                                      <ArrowUp className="w-3 h-3" />
                                    </Button>
                                    <Button
                                      type="button"
                                      variant="ghost"
                                      size="icon"
                                      className="h-5 w-5 p-0 rounded"
                                      onClick={() => moveElemento(index, 1)}
                                      disabled={index === selectedElementos.length - 1}
                                    >
                                      <ArrowDown className="w-3 h-3" />
                                    </Button>
                                  </div>
                                  <Badge variant="outline" className="rounded-full">{index + 1}</Badge>
                                  <span className="text-sm flex-1 text-ui">{elemento.nombre}</span>
                                </div>
                              ))}
                            </div>
                          </div>

                          <div>
                            <Label>Preview del Material</Label>
                            <Tabs defaultValue={String(0)} className="w-full">
                              <TabsList className="grid w-full" style={{ gridTemplateColumns: `repeat(${Math.min(selectedElementos.length, 4)}, 1fr)` }}>
                                {selectedElementos.slice(0, 4).map((elemento, idx) => (
                                  <TabsTrigger key={idx} value={String(idx)} className="text-xs truncate">
                                    {elemento.nombre}
                                  </TabsTrigger>
                                ))}
                                {selectedElementos.length > 4 && (
                                  <TabsTrigger value="more" className="text-xs truncate" disabled>
                                    ... {selectedElementos.length - 4} más
                                  </TabsTrigger>
                                )}
                              </TabsList>
                              {selectedElementos.map((elemento, idx) => (
                                <TabsContent key={idx} value={String(idx)} className="space-y-2">
                                  {elemento.media?.video && (
                                    <div className="border border-[var(--color-border-default)] rounded-xl p-2 bg-card">
                                      <div className="flex items-center gap-2 text-sm mb-1">
                                        <Play className="w-4 h-4 text-blue-600" />
                                        <span className="font-medium text-ui">Video</span>
                                      </div>
                                      <a href={elemento.media.video} target="_blank" rel="noopener noreferrer" className="text-xs text-blue-600 hover:underline truncate block">
                                        {elemento.media.video}
                                      </a>
                                    </div>
                                  )}
                                  {elemento.media?.audio && (
                                    <div className="border border-[var(--color-border-default)] rounded-xl p-2 bg-card">
                                      <div className="flex items-center gap-2 text-sm mb-1">
                                        <Volume2 className="w-4 h-4 text-purple-600" />
                                        <span className="font-medium text-ui">Audio</span>
                                      </div>
                                      <a href={elemento.media.audio} target="_blank" rel="noopener noreferrer" className="text-xs text-purple-600 hover:underline truncate block">
                                        {elemento.media.audio}
                                      </a>
                                    </div>
                                  )}
                                  {elemento.media?.imagen && (
                                    <div className="border border-[var(--color-border-default)] rounded-xl p-2 bg-card">
                                      <div className="flex items-center gap-2 text-sm mb-1">
                                        <ImageIcon className="w-4 h-4 text-green-600" />
                                        <span className="font-medium text-ui">Imagen</span>
                                      </div>
                                      <a href={elemento.media.imagen} target="_blank" rel="noopener noreferrer" className="text-xs text-green-600 hover:underline truncate block">
                                        {elemento.media.imagen}
                                      </a>
                                    </div>
                                  )}
                                  {elemento.media?.pdf && (
                                    <div className="border border-[var(--color-border-default)] rounded-xl p-2 bg-card">
                                      <div className="flex items-center gap-2 text-sm mb-1">
                                        <FileText className="w-4 h-4 text-red-600" />
                                        <span className="font-medium text-ui">PDF</span>
                                      </div>
                                      <a href={elemento.media.pdf} target="_blank" rel="noopener noreferrer" className="text-xs text-red-600 hover:underline truncate block">
                                        {elemento.media.pdf}
                                      </a>
                                    </div>
                                  )}
                                  {!elemento.media?.video && !elemento.media?.audio && !elemento.media?.imagen && !elemento.media?.pdf && (
                                    <p className="text-xs text-[var(--color-text-secondary)] text-center py-4">Sin material multimedia</p>
                                  )}
                                </TabsContent>
                              ))}
                            </Tabs>
                          </div>
                        </>
                      )}
                    </>
                  )}

                  {elementosDisponibles.length === 0 && isFM && (
                    <Alert className="rounded-xl border-amber-200 bg-amber-50">
                      <AlertTriangle className="h-4 w-4 text-amber-600" />
                      <AlertDescription className="text-amber-700 text-sm">
                        {usandoPiezaSnapshot ? 
                          'La pieza de la asignación no tiene elementos' : 
                          'Selecciona una pieza con elementos para configurar FM'}
                      </AlertDescription>
                    </Alert>
                  )}
                </CardContent>
              </Card>
            )}

            <Card className="app-panel">
              <CardHeader>
                <CardTitle>Materiales Requeridos</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex gap-2">
                  <Input
                    placeholder="Ej: Metrónomo, partitura..."
                    value={nuevoMaterial}
                    onChange={(e) => setNuevoMaterial(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addMaterial())}
                    className="h-10 rounded-xl border-[var(--color-border-default)] focus-orange"
                  />
                  <Button onClick={addMaterial} type="button" className="h-10 rounded-xl btn-primary shadow-sm">
                    <Plus className="w-4 h-4" />
                  </Button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {formData.materialesRequeridos.map((material, index) => (
                    <Badge key={index} variant="secondary" className="flex items-center gap-1 rounded-full">
                      {material}
                      <button
                        onClick={() => removeMaterial(index)}
                        className="ml-1 hover:text-red-600"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>

            {!isFM && (
              <Card className="app-panel">
                <CardHeader>
                  <CardTitle>Multimedia</CardTitle>
                </CardHeader>
                <CardContent className="p-6 pt-0">
                  <MediaLinksInput
                    value={formData.mediaLinks || []}
                    onChange={(links) => setFormData({ ...formData, mediaLinks: normalizeMediaLinks(links) })}
                  />
                </CardContent>
              </Card>
            )}
          </div>

          <div className="border-t border-[var(--color-border-default)] px-6 py-4 bg-[var(--color-surface-muted)] rounded-b-2xl">
            <div className="flex gap-3 mb-2">
              <Button variant="outline" onClick={() => onClose(null)} className={`flex-1 ${componentStyles.buttons.outline}`}>
                Cancelar
              </Button>
              <Button
                onClick={handleSave}
                disabled={saveMutation.isPending}
                className={`flex-1 ${componentStyles.buttons.primary}`}
              >
                {saveMutation.isPending ? (
                  'Guardando...'
                ) : (
                  <>
                    <Save className="w-4 h-4 mr-2" />
                    Guardar
                  </>
                )}
              </Button>
            </div>
            <p className="text-xs text-center text-[var(--color-text-secondary)]">
              Ctrl/⌘+. : cerrar • Ctrl/⌘+Intro : guardar
            </p>
          </div>
        </div>
      </div>
    </>
  );

  return createPortal(modalContent, document.body);
}
